dist: trusty
language: java
sudo: false
jdk:
- oraclejdk11
before_install:
- export TZ=Brazil/East
deploy:
  provider: heroku
  app: apis-admin-server
  api_key:
    secure: Ub6Rhq2No8O2ot5XaKgw2H3pkRYBK1DBuxyjm34Yk9JIG1+GKoKqvghMO65FjrdRfSVe2yEXaH9tcd8+lpxAqSibkLDo7LTCImBN7GbeYtFPUH2tRHGb2nSgnMAhQde0EGXvqBI30EQEkgzTGhJeANw07e7fAJddt3H2PP5xhzpXwxHNKGiD1Wn6xfAIuMDS7+gjWvUfZbHFNiaigpiBNLhOmzFRxpxIrBI+4SjVZvV2rWJL3e0B6KUDgz8IIzAmHh+EsSZ/CkzPqAV9k4HENTrkhxr8v5bg3fMluUF+vf35X8RKrfv7O/qS8nZR6pBurMguut09lTjtVcD0JAkyL4j+w1vW2DCqn1+EDk7tlT9Y84fXEFFAIMu6qzQ4en5OihVG978SqR9YOMAZ++SKKPkYb1xV7OtQyzfc8dj1C3yIm5aCSHDNKuCCDN055rAV4HnUL8FrzZ64GPkcSSpQGh9yVyuubD6hoCYy3q75MOKe39S3EafpuTs3ltVeElGvXcQJ4QREKiwnkFC1P1kRB8nHY8cvOwpY0E2QeMzTlR4owm9WeFm2vecPORtADSjvmVjwkj/idJd0+OGc/mkqUNhVdh1o8wP0whEk93uD7YN6LejV2O9gE5m7o8QzwsdciL8mRpFZkuGRuWkSg5+B8TuCJTadWSrkUxulrcXu66c=
